#不同环境切换配置之：开发环境
server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itsdf07_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

versionFlag: dev