server:
  port: 8087
  servlet:
    context-path: /itsdf07

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/itsdf07_db?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.itsdf07.entity  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 配置控制台打印sql查询语句并附带查询结果数据
