server:
  port: 8087
  servlet:
    context-path: /itsdf07

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itsdf07_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  #  ###ThymeLeaf配置
thymeleaf:
  ##配置模板引擎:是让controller层到templates文件夹寻找xx.html(src/main/resources/templates)
  prefix: classpath:/templates/ #配置前缀，可以不配置，因为静态页面存放的默认位置就是该templates
  suffix: .html #配置后缀，也是可以不用配置，也是默认html
  cache: false
  encoding: UTF-8
  content-type: text/html; charse=utf-8

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.itsdf07.entity  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 配置控制台打印sql查询语句并附带查询结果数据
